version = 1

[[analyzers]]
name = "javascript"
[analyzers.meta]
  environment = ["nodejs", "jquery"]
  dialect = "typescript"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"
